package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicBank extends BaseDicBank<DicBank> {
	public static final DicBank dao = new DicBank().dao();
}
