package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicDict extends BaseDicDict<DicDict> {
	public static final DicDict dao = new DicDict().dao();
}
