package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicFormats;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicFormats extends BaseDicFormats<DicFormats> {
	public static final DicFormats dao = new DicFormats().dao();
}
