package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicGoodsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicGoodsType extends BaseDicGoodsType<DicGoodsType> {
	public static final DicGoodsType dao = new DicGoodsType().dao();
}
