package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicHomeModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicHomeModule extends BaseDicHomeModule<DicHomeModule> {
	public static final DicHomeModule dao = new DicHomeModule().dao();
}
