package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicLoanBank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicLoanBank extends BaseDicLoanBank<DicLoanBank> {
	public static final DicLoanBank dao = new DicLoanBank().dao();
}
