package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDicPaymethods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicPaymethods extends BaseDicPaymethods<DicPaymethods> {
	public static final DicPaymethods dao = new DicPaymethods().dao();
}
