package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtAgreementState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtAgreementState extends BaseDtAgreementState<DtAgreementState> {
	public static final DtAgreementState dao = new DtAgreementState().dao();
}
