package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBankScheduling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBankScheduling extends BaseDtBankScheduling<DtBankScheduling> {
	public static final DtBankScheduling dao = new DtBankScheduling().dao();
}
