package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingAcceptanceTaskProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingAcceptanceTaskProject extends BaseDtBuildingAcceptanceTaskProject<DtBuildingAcceptanceTaskProject> {
	public static final DtBuildingAcceptanceTaskProject dao = new DtBuildingAcceptanceTaskProject().dao();
}
