package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingAcceptanceTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingAcceptanceTask extends BaseDtBuildingAcceptanceTask<DtBuildingAcceptanceTask> {
	public static final DtBuildingAcceptanceTask dao = new DtBuildingAcceptanceTask().dao();
}
