package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingReserved;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingReserved extends BaseDtBuildingReserved<DtBuildingReserved> {
	public static final DtBuildingReserved dao = new DtBuildingReserved().dao();
}
