package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingAcceptanceTaskAcceptance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingAcceptanceTaskAcceptance extends BaseDtBuildingAcceptanceTaskAcceptance<DtBuildingAcceptanceTaskAcceptance> {
	public static final DtBuildingAcceptanceTaskAcceptance dao = new DtBuildingAcceptanceTaskAcceptance().dao();
}
