package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingAcceptance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingAcceptance extends BaseDtBuildingAcceptance<DtBuildingAcceptance> {
	public static final DtBuildingAcceptance dao = new DtBuildingAcceptance().dao();
}
