package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtBuildingAcceptor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtBuildingAcceptor extends BaseDtBuildingAcceptor<DtBuildingAcceptor> {
	public static final DtBuildingAcceptor dao = new DtBuildingAcceptor().dao();
}
