package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtContractInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtContractInfo extends BaseDtContractInfo<DtContractInfo> {
	public static final DtContractInfo dao = new DtContractInfo().dao();
}
