package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDetailListState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDetailListState extends BaseDtDetailListState<DtDetailListState> {
	public static final DtDetailListState dao = new DtDetailListState().dao();
}
