package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDeedtaxResults;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDeedtaxResults extends BaseDtDeedtaxResults<DtDeedtaxResults> {
	public static final DtDeedtaxResults dao = new DtDeedtaxResults().dao();
}
