package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDetailList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDetailList extends BaseDtDetailList<DtDetailList> {
	public static final DtDetailList dao = new DtDetailList().dao();
}
