package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDeedtaxReturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDeedtaxReturn extends BaseDtDeedtaxReturn<DtDeedtaxReturn> {
	public static final DtDeedtaxReturn dao = new DtDeedtaxReturn().dao();
}
