package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDetailListType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDetailListType extends BaseDtDetailListType<DtDetailListType> {
	public static final DtDetailListType dao = new DtDetailListType().dao();
}
