package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtDuty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtDuty extends BaseDtDuty<DtDuty> {
	public static final DtDuty dao = new DtDuty().dao();
}
