package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtFormId;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtFormId extends BaseDtFormId<DtFormId> {
	public static final DtFormId dao = new DtFormId().dao();
}
