package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtGoods extends BaseDtGoods<DtGoods> {
	public static final DtGoods dao = new DtGoods().dao();
}
