package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtHousePersonalInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtHousePersonalInformation extends BaseDtHousePersonalInformation<DtHousePersonalInformation> {
	public static final DtHousePersonalInformation dao = new DtHousePersonalInformation().dao();
}
