package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtHouseCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtHouseCar extends BaseDtHouseCar<DtHouseCar> {
	public static final DtHouseCar dao = new DtHouseCar().dao();
}
