package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtHouseDecorate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtHouseDecorate extends BaseDtHouseDecorate<DtHouseDecorate> {
	public static final DtHouseDecorate dao = new DtHouseDecorate().dao();
}
