package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtHouseHobby;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtHouseHobby extends BaseDtHouseHobby<DtHouseHobby> {
	public static final DtHouseHobby dao = new DtHouseHobby().dao();
}
