package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtHouseCohabitation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtHouseCohabitation extends BaseDtHouseCohabitation<DtHouseCohabitation> {
	public static final DtHouseCohabitation dao = new DtHouseCohabitation().dao();
}
