package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtMaterials;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtMaterials extends BaseDtMaterials<DtMaterials> {
	public static final DtMaterials dao = new DtMaterials().dao();
}
