package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtMetaValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtMetaValue extends BaseDtMetaValue<DtMetaValue> {
	public static final DtMetaValue dao = new DtMetaValue().dao();
}
