package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtMortgageInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtMortgageInformation extends BaseDtMortgageInformation<DtMortgageInformation> {
	public static final DtMortgageInformation dao = new DtMortgageInformation().dao();
}
