package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtMortgageInformationUpdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtMortgageInformationUpdate extends BaseDtMortgageInformationUpdate<DtMortgageInformationUpdate> {
	public static final DtMortgageInformationUpdate dao = new DtMortgageInformationUpdate().dao();
}
