package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtNeedUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtNeedUpload extends BaseDtNeedUpload<DtNeedUpload> {
	public static final DtNeedUpload dao = new DtNeedUpload().dao();
}
