package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtPropertyOwners;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtPropertyOwners extends BaseDtPropertyOwners<DtPropertyOwners> {
	public static final DtPropertyOwners dao = new DtPropertyOwners().dao();
}
