package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtPropertyOwnersUpdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtPropertyOwnersUpdate extends BaseDtPropertyOwnersUpdate<DtPropertyOwnersUpdate> {
	public static final DtPropertyOwnersUpdate dao = new DtPropertyOwnersUpdate().dao();
}
