package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtReadmeFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtReadmeFiles extends BaseDtReadmeFiles<DtReadmeFiles> {
	public static final DtReadmeFiles dao = new DtReadmeFiles().dao();
}
