package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtReadmeStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtReadmeStage extends BaseDtReadmeStage<DtReadmeStage> {
	public static final DtReadmeStage dao = new DtReadmeStage().dao();
}
