package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtRecordOperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtRecordOperation extends BaseDtRecordOperation<DtRecordOperation> {
	public static final DtRecordOperation dao = new DtRecordOperation().dao();
}
