package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtReadme;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtReadme extends BaseDtReadme<DtReadme> {
	public static final DtReadme dao = new DtReadme().dao();
}
