package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtScanRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtScanRecord extends BaseDtScanRecord<DtScanRecord> {
	public static final DtScanRecord dao = new DtScanRecord().dao();
}
