package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtStoreFiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtStoreFiles extends BaseDtStoreFiles<DtStoreFiles> {
	public static final DtStoreFiles dao = new DtStoreFiles().dao();
}
