package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtUserFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtUserFeedback extends BaseDtUserFeedback<DtUserFeedback> {
	public static final DtUserFeedback dao = new DtUserFeedback().dao();
}
