package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtUserInfoRelateValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtUserInfoRelateValue extends BaseDtUserInfoRelateValue<DtUserInfoRelateValue> {
	public static final DtUserInfoRelateValue dao = new DtUserInfoRelateValue().dao();
}
