package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtUserMessage extends BaseDtUserMessage<DtUserMessage> {
	public static final DtUserMessage dao = new DtUserMessage().dao();
}
