package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseDtUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DtUserInfo extends BaseDtUserInfo<DtUserInfo> {
	public static final DtUserInfo dao = new DtUserInfo().dao();
}
