package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseScOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScOrder extends BaseScOrder<ScOrder> {
	public static final ScOrder dao = new ScOrder().dao();
}
