package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynBuildingAcceptanceError;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynBuildingAcceptanceError extends BaseSynBuildingAcceptanceError<SynBuildingAcceptanceError> {
	public static final SynBuildingAcceptanceError dao = new SynBuildingAcceptanceError().dao();
}
