package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynBankOperator;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynBankOperator extends BaseSynBankOperator<SynBankOperator> {
	public static final SynBankOperator dao = new SynBankOperator().dao();
}
