package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynBuildingAcceptance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynBuildingAcceptance extends BaseSynBuildingAcceptance<SynBuildingAcceptance> {
	public static final SynBuildingAcceptance dao = new SynBuildingAcceptance().dao();
}
