package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynBuildingInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynBuildingInfo extends BaseSynBuildingInfo<SynBuildingInfo> {
	public static final SynBuildingInfo dao = new SynBuildingInfo().dao();
}
