package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynCertificateType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynCertificateType extends BaseSynCertificateType<SynCertificateType> {
	public static final SynCertificateType dao = new SynCertificateType().dao();
}
