package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynCompany extends BaseSynCompany<SynCompany> {
	public static final SynCompany dao = new SynCompany().dao();
}
