package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynOrderErrorinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynOrderErrorinfo extends BaseSynOrderErrorinfo<SynOrderErrorinfo> {
	public static final SynOrderErrorinfo dao = new SynOrderErrorinfo().dao();
}
