package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynOrder extends BaseSynOrder<SynOrder> {
	public static final SynOrder dao = new SynOrder().dao();
}
