package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynPaymethods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynPaymethods extends BaseSynPaymethods<SynPaymethods> {
	public static final SynPaymethods dao = new SynPaymethods().dao();
}
