package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynPropertyOwners;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynPropertyOwners extends BaseSynPropertyOwners<SynPropertyOwners> {
	public static final SynPropertyOwners dao = new SynPropertyOwners().dao();
}
