package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynProjectStage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynProjectStage extends BaseSynProjectStage<SynProjectStage> {
	public static final SynProjectStage dao = new SynProjectStage().dao();
}
