package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynPaidMoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynPaidMoney extends BaseSynPaidMoney<SynPaidMoney> {
	public static final SynPaidMoney dao = new SynPaidMoney().dao();
}
