package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSynServices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SynServices extends BaseSynServices<SynServices> {
	public static final SynServices dao = new SynServices().dao();
}
