package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSysAccounts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysAccounts extends BaseSysAccounts<SysAccounts> {
	public static final SysAccounts dao = new SysAccounts().dao();
}
