package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseSysLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLoginLog extends BaseSysLoginLog<SysLoginLog> {
	public static final SysLoginLog dao = new SysLoginLog().dao();
}
