package com.demo.api.jfinal.model;

import com.demo.api.jfinal.model.base.BaseWxStepRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxStepRecord extends BaseWxStepRecord<WxStepRecord> {
	public static final WxStepRecord dao = new WxStepRecord().dao();
}
