package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtHouseCohabitation<M extends BaseDtHouseCohabitation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setCohabitationName(java.lang.String cohabitationName) {
		set("cohabitation_name", cohabitationName);
	}
	
	public java.lang.String getCohabitationName() {
		return getStr("cohabitation_name");
	}

	public void setProprietorRelation(java.lang.String proprietorRelation) {
		set("proprietor_relation", proprietorRelation);
	}
	
	public java.lang.String getProprietorRelation() {
		return getStr("proprietor_relation");
	}

	public void setBirthday(java.lang.String birthday) {
		set("birthday", birthday);
	}
	
	public java.lang.String getBirthday() {
		return getStr("birthday");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setLifeState(java.lang.String lifeState) {
		set("life_state", lifeState);
	}
	
	public java.lang.String getLifeState() {
		return getStr("life_state");
	}

	public void setOrder(java.lang.String order) {
		set("order", order);
	}
	
	public java.lang.String getOrder() {
		return getStr("order");
	}

	public void setCloseStatus(java.lang.Boolean closeStatus) {
		set("close_status", closeStatus);
	}
	
	public java.lang.Boolean getCloseStatus() {
		return get("close_status");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
