package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtMortgageInformation<M extends BaseDtMortgageInformation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMortgage(java.lang.String mortgage) {
		set("mortgage", mortgage);
	}
	
	public java.lang.String getMortgage() {
		return getStr("mortgage");
	}

	public void setBankId(java.lang.String bankId) {
		set("bank_id", bankId);
	}
	
	public java.lang.String getBankId() {
		return getStr("bank_id");
	}

	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}
	
	public java.lang.String getManager() {
		return getStr("manager");
	}

	public void setLoanPeriod(java.lang.Integer loanPeriod) {
		set("loan_period", loanPeriod);
	}
	
	public java.lang.Integer getLoanPeriod() {
		return getInt("loan_period");
	}

	public void setLoanAmount(java.math.BigDecimal loanAmount) {
		set("loan_amount", loanAmount);
	}
	
	public java.math.BigDecimal getLoanAmount() {
		return get("loan_amount");
	}

	public void setLoanRatio(java.lang.String loanRatio) {
		set("loan_ratio", loanRatio);
	}
	
	public java.lang.String getLoanRatio() {
		return getStr("loan_ratio");
	}

	public void setFundAmount(java.math.BigDecimal fundAmount) {
		set("fund_amount", fundAmount);
	}
	
	public java.math.BigDecimal getFundAmount() {
		return get("fund_amount");
	}

	public void setContractInfoId(java.lang.Integer contractInfoId) {
		set("contract_info_id", contractInfoId);
	}
	
	public java.lang.Integer getContractInfoId() {
		return getInt("contract_info_id");
	}

	public void setOrderBy(java.lang.Integer orderBy) {
		set("order_by", orderBy);
	}
	
	public java.lang.Integer getOrderBy() {
		return getInt("order_by");
	}

	public void setPayId(java.lang.String payId) {
		set("pay_id", payId);
	}
	
	public java.lang.String getPayId() {
		return getStr("pay_id");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

}
