package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynPropertyOwners<M extends BaseSynPropertyOwners<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOwnerId(java.lang.String ownerId) {
		set("owner_id", ownerId);
	}
	
	public java.lang.String getOwnerId() {
		return getStr("owner_id");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public void setCertificateType(java.lang.String certificateType) {
		set("certificate_type", certificateType);
	}
	
	public java.lang.String getCertificateType() {
		return getStr("certificate_type");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setOwnPercent(java.math.BigDecimal ownPercent) {
		set("own_percent", ownPercent);
	}
	
	public java.math.BigDecimal getOwnPercent() {
		return get("own_percent");
	}

	public void setIsPrimary(java.lang.Boolean isPrimary) {
		set("is_primary", isPrimary);
	}
	
	public java.lang.Boolean getIsPrimary() {
		return get("is_primary");
	}

	public void setAgenterName(java.lang.String agenterName) {
		set("agenter_name", agenterName);
	}
	
	public java.lang.String getAgenterName() {
		return getStr("agenter_name");
	}

	public void setAgenterCountry(java.lang.String agenterCountry) {
		set("agenter_country", agenterCountry);
	}
	
	public java.lang.String getAgenterCountry() {
		return getStr("agenter_country");
	}

	public void setAgenterIdCard(java.lang.String agenterIdCard) {
		set("agenter_id_card", agenterIdCard);
	}
	
	public java.lang.String getAgenterIdCard() {
		return getStr("agenter_id_card");
	}

	public void setAgenterMobile(java.lang.String agenterMobile) {
		set("agenter_mobile", agenterMobile);
	}
	
	public java.lang.String getAgenterMobile() {
		return getStr("agenter_mobile");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

}
