package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtContractInfo<M extends BaseDtContractInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCrmContractId(java.lang.String crmContractId) {
		set("crm_contract_id", crmContractId);
	}
	
	public java.lang.String getCrmContractId() {
		return getStr("crm_contract_id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setCounselor(java.lang.String counselor) {
		set("counselor", counselor);
	}
	
	public java.lang.String getCounselor() {
		return getStr("counselor");
	}

	public void setCounselorMobile(java.lang.String counselorMobile) {
		set("counselor_mobile", counselorMobile);
	}
	
	public java.lang.String getCounselorMobile() {
		return getStr("counselor_mobile");
	}

	public void setBelongProject(java.lang.String belongProject) {
		set("belong_project", belongProject);
	}
	
	public java.lang.String getBelongProject() {
		return getStr("belong_project");
	}

	public void setBelongCompany(java.lang.String belongCompany) {
		set("belong_company", belongCompany);
	}
	
	public java.lang.String getBelongCompany() {
		return getStr("belong_company");
	}

	public void setOrderStatus(java.lang.String orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.String getOrderStatus() {
		return getStr("order_status");
	}

	public void setSonStatus(java.lang.String sonStatus) {
		set("son_status", sonStatus);
	}
	
	public java.lang.String getSonStatus() {
		return getStr("son_status");
	}

	public void setReservationType(java.lang.Integer reservationType) {
		set("reservation_type", reservationType);
	}
	
	public java.lang.Integer getReservationType() {
		return getInt("reservation_type");
	}

	public void setBelongAccount(java.lang.Integer belongAccount) {
		set("belong_account", belongAccount);
	}
	
	public java.lang.Integer getBelongAccount() {
		return getInt("belong_account");
	}

	public void setIsDrawback(java.lang.Boolean isDrawback) {
		set("is_drawback", isDrawback);
	}
	
	public java.lang.Boolean getIsDrawback() {
		return get("is_drawback");
	}

	public void setDrawbackResult(java.lang.String drawbackResult) {
		set("drawback_result", drawbackResult);
	}
	
	public java.lang.String getDrawbackResult() {
		return getStr("drawback_result");
	}

	public void setDeedtaxMaterialsId(java.lang.Integer deedtaxMaterialsId) {
		set("deedtax_materials_id", deedtaxMaterialsId);
	}
	
	public java.lang.Integer getDeedtaxMaterialsId() {
		return getInt("deedtax_materials_id");
	}

	public void setIsByStages(java.lang.Boolean isByStages) {
		set("is_by_stages", isByStages);
	}
	
	public java.lang.Boolean getIsByStages() {
		return get("is_by_stages");
	}

	public void setPaymentMethod(java.lang.Integer paymentMethod) {
		set("payment_method", paymentMethod);
	}
	
	public java.lang.Integer getPaymentMethod() {
		return getInt("payment_method");
	}

	public void setLoanMaterialsId(java.lang.Integer loanMaterialsId) {
		set("loan_materials_id", loanMaterialsId);
	}
	
	public java.lang.Integer getLoanMaterialsId() {
		return getInt("loan_materials_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setIsCandrawback(java.lang.Boolean isCandrawback) {
		set("is_candrawback", isCandrawback);
	}
	
	public java.lang.Boolean getIsCandrawback() {
		return get("is_candrawback");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setFinishTime(java.util.Date finishTime) {
		set("finish_time", finishTime);
	}
	
	public java.util.Date getFinishTime() {
		return get("finish_time");
	}

}
