package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtDetailListType<M extends BaseDtDetailListType<M>> extends Model<M> implements IBean {

	public void setDetailListId(java.lang.Integer detailListId) {
		set("detail_list_id", detailListId);
	}
	
	public java.lang.Integer getDetailListId() {
		return getInt("detail_list_id");
	}

	public void setGoodsTypeId(java.lang.Integer goodsTypeId) {
		set("goods_type_id", goodsTypeId);
	}
	
	public java.lang.Integer getGoodsTypeId() {
		return getInt("goods_type_id");
	}

}
