package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynBankOperator<M extends BaseSynBankOperator<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOperatorId(java.lang.String operatorId) {
		set("operator_id", operatorId);
	}
	
	public java.lang.String getOperatorId() {
		return getStr("operator_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setNameAcronym(java.lang.String nameAcronym) {
		set("name_acronym", nameAcronym);
	}
	
	public java.lang.String getNameAcronym() {
		return getStr("name_acronym");
	}

	public void setBankId(java.lang.String bankId) {
		set("bank_id", bankId);
	}
	
	public java.lang.String getBankId() {
		return getStr("bank_id");
	}

}
