package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysAccounts<M extends BaseSysAccounts<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}
	
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	public java.lang.String getSalt() {
		return getStr("salt");
	}

	public void setWechatId(java.lang.String wechatId) {
		set("wechat_id", wechatId);
	}
	
	public java.lang.String getWechatId() {
		return getStr("wechat_id");
	}

	public void setIsActived(java.lang.Boolean isActived) {
		set("is_actived", isActived);
	}
	
	public java.lang.Boolean getIsActived() {
		return get("is_actived");
	}

	public void setStatusCode(java.lang.String statusCode) {
		set("status_code", statusCode);
	}
	
	public java.lang.String getStatusCode() {
		return getStr("status_code");
	}

	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setActiveTime(java.util.Date activeTime) {
		set("active_time", activeTime);
	}
	
	public java.util.Date getActiveTime() {
		return get("active_time");
	}

	public void setWxName(java.lang.String wxName) {
		set("wx_name", wxName);
	}
	
	public java.lang.String getWxName() {
		return getStr("wx_name");
	}

}
