package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtBuildingReserved<M extends BaseDtBuildingReserved<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setDateType(java.lang.String dateType) {
		set("date_type", dateType);
	}
	
	public java.lang.String getDateType() {
		return getStr("date_type");
	}

	public void setDateDetail(java.lang.String dateDetail) {
		set("date_detail", dateDetail);
	}
	
	public java.lang.String getDateDetail() {
		return getStr("date_detail");
	}

	public void setReservedCount(java.lang.Integer reservedCount) {
		set("reserved_count", reservedCount);
	}
	
	public java.lang.Integer getReservedCount() {
		return getInt("reserved_count");
	}

	public void setDutyId(java.lang.Integer dutyId) {
		set("duty_id", dutyId);
	}
	
	public java.lang.Integer getDutyId() {
		return getInt("duty_id");
	}

}
