package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynOrderErrorinfo<M extends BaseSynOrderErrorinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setErrorMessge(java.lang.String errorMessge) {
		set("error_messge", errorMessge);
	}
	
	public java.lang.String getErrorMessge() {
		return getStr("error_messge");
	}

	public void setOrderMessage(java.lang.String orderMessage) {
		set("order_message", orderMessage);
	}
	
	public java.lang.String getOrderMessage() {
		return getStr("order_message");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
