package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtBuildingAcceptanceTaskAcceptance<M extends BaseDtBuildingAcceptanceTaskAcceptance<M>> extends Model<M> implements IBean {

	public void setTaskId(java.lang.Integer taskId) {
		set("task_id", taskId);
	}
	
	public java.lang.Integer getTaskId() {
		return getInt("task_id");
	}

	public void setAcceptanceId(java.lang.Integer acceptanceId) {
		set("acceptance_id", acceptanceId);
	}
	
	public java.lang.Integer getAcceptanceId() {
		return getInt("acceptance_id");
	}

}
