package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynBuildingAcceptanceError<M extends BaseSynBuildingAcceptanceError<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDataType(java.lang.String dataType) {
		set("data_type", dataType);
	}
	
	public java.lang.String getDataType() {
		return getStr("data_type");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setStageId(java.lang.String stageId) {
		set("stage_id", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stage_id");
	}

	public void setStageName(java.lang.String stageName) {
		set("stage_name", stageName);
	}
	
	public java.lang.String getStageName() {
		return getStr("stage_name");
	}

	public void setBuildingId(java.lang.String buildingId) {
		set("building_Id", buildingId);
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_Id");
	}

	public void setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public void setRoom(java.lang.String room) {
		set("room", room);
	}
	
	public java.lang.String getRoom() {
		return getStr("room");
	}

	public void setAcceptTime(java.util.Date acceptTime) {
		set("accept_time", acceptTime);
	}
	
	public java.util.Date getAcceptTime() {
		return get("accept_time");
	}

	public void setBeginDeliverTime(java.util.Date beginDeliverTime) {
		set("begin_deliver_time", beginDeliverTime);
	}
	
	public java.util.Date getBeginDeliverTime() {
		return get("begin_deliver_time");
	}

	public void setActualDeliverTime(java.util.Date actualDeliverTime) {
		set("actual_deliver_time", actualDeliverTime);
	}
	
	public java.util.Date getActualDeliverTime() {
		return get("actual_deliver_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
