package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynBuildingInfo<M extends BaseSynBuildingInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setRoom(java.lang.String room) {
		set("room", room);
	}
	
	public java.lang.String getRoom() {
		return getStr("room");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setArea(java.math.BigDecimal area) {
		set("area", area);
	}
	
	public java.math.BigDecimal getArea() {
		return get("area");
	}

	public void setInnerArea(java.math.BigDecimal innerArea) {
		set("inner_area", innerArea);
	}
	
	public java.math.BigDecimal getInnerArea() {
		return get("inner_area");
	}

	public void setBuildingType(java.lang.String buildingType) {
		set("building_type", buildingType);
	}
	
	public java.lang.String getBuildingType() {
		return getStr("building_type");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setDoor(java.lang.String door) {
		set("door", door);
	}
	
	public java.lang.String getDoor() {
		return getStr("door");
	}

	public void setRealArea(java.math.BigDecimal realArea) {
		set("real_area", realArea);
	}
	
	public java.math.BigDecimal getRealArea() {
		return get("real_area");
	}

	public void setRealInnerArea(java.math.BigDecimal realInnerArea) {
		set("real_inner_area", realInnerArea);
	}
	
	public java.math.BigDecimal getRealInnerArea() {
		return get("real_inner_area");
	}

}
