package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtGoods<M extends BaseDtGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}
	
	public java.lang.String getAmount() {
		return getStr("amount");
	}

	public void setFileId(java.lang.Integer fileId) {
		set("file_id", fileId);
	}
	
	public java.lang.Integer getFileId() {
		return getInt("file_id");
	}

	public void setGoodsTypeId(java.lang.Integer goodsTypeId) {
		set("goods_type_id", goodsTypeId);
	}
	
	public java.lang.Integer getGoodsTypeId() {
		return getInt("goods_type_id");
	}

	public void setDetailListId(java.lang.Integer detailListId) {
		set("detail_list_id", detailListId);
	}
	
	public java.lang.Integer getDetailListId() {
		return getInt("detail_list_id");
	}

}
