package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynProjectStage<M extends BaseSynProjectStage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setStageId(java.lang.String stageId) {
		set("stage_id", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stage_id");
	}

	public void setStageName(java.lang.String stageName) {
		set("stage_name", stageName);
	}
	
	public java.lang.String getStageName() {
		return getStr("stage_name");
	}

	public void setStageCardId(java.lang.String stageCardId) {
		set("stage_card_id", stageCardId);
	}
	
	public java.lang.String getStageCardId() {
		return getStr("stage_card_id");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setBusinessName(java.lang.String businessName) {
		set("business_name", businessName);
	}
	
	public java.lang.String getBusinessName() {
		return getStr("business_name");
	}

	public void setProjectCardId(java.lang.String projectCardId) {
		set("project_card_id", projectCardId);
	}
	
	public java.lang.String getProjectCardId() {
		return getStr("project_card_id");
	}

	public void setApproveTime(java.lang.String approveTime) {
		set("approve_time", approveTime);
	}
	
	public java.lang.String getApproveTime() {
		return getStr("approve_time");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}
	
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public void setModifiedTime(java.lang.String modifiedTime) {
		set("modified_time", modifiedTime);
	}
	
	public java.lang.String getModifiedTime() {
		return getStr("modified_time");
	}

	public void setLastSynchronizeTime(java.lang.String lastSynchronizeTime) {
		set("last_synchronize_time", lastSynchronizeTime);
	}
	
	public java.lang.String getLastSynchronizeTime() {
		return getStr("last_synchronize_time");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("company_code", companyCode);
	}
	
	public java.lang.String getCompanyCode() {
		return getStr("company_code");
	}

}
