package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtUserInfo<M extends BaseDtUserInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBuildingAcceptanceId(java.lang.Integer buildingAcceptanceId) {
		set("building_acceptance_id", buildingAcceptanceId);
	}
	
	public java.lang.Integer getBuildingAcceptanceId() {
		return getInt("building_acceptance_id");
	}

	public void setInfoType(java.lang.String infoType) {
		set("info_type", infoType);
	}
	
	public java.lang.String getInfoType() {
		return getStr("info_type");
	}

	public void setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
	}
	
	public java.lang.Integer getTemplateId() {
		return getInt("template_id");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}
	
	public java.lang.Integer getVersion() {
		return getInt("version");
	}

}
