package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynBuildingAcceptance<M extends BaseSynBuildingAcceptance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setStageId(java.lang.String stageId) {
		set("stage_id", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stage_id");
	}

	public void setStageName(java.lang.String stageName) {
		set("stage_name", stageName);
	}
	
	public java.lang.String getStageName() {
		return getStr("stage_name");
	}

	public void setBuildingId(java.lang.String buildingId) {
		set("building_Id", buildingId);
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_Id");
	}

	public void setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public void setRoom(java.lang.String room) {
		set("room", room);
	}
	
	public java.lang.String getRoom() {
		return getStr("room");
	}

	public void setAcceptTime(java.util.Date acceptTime) {
		set("accept_time", acceptTime);
	}
	
	public java.util.Date getAcceptTime() {
		return get("accept_time");
	}

	public void setBeginDeliverTime(java.util.Date beginDeliverTime) {
		set("begin_deliver_time", beginDeliverTime);
	}
	
	public java.util.Date getBeginDeliverTime() {
		return get("begin_deliver_time");
	}

	public void setActualDeliverTime(java.util.Date actualDeliverTime) {
		set("actual_deliver_time", actualDeliverTime);
	}
	
	public java.util.Date getActualDeliverTime() {
		return get("actual_deliver_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setAreaSupplement(java.math.BigDecimal areaSupplement) {
		set("area_supplement", areaSupplement);
	}
	
	public java.math.BigDecimal getAreaSupplement() {
		return get("area_supplement");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setBuildingType(java.lang.String buildingType) {
		set("building_type", buildingType);
	}
	
	public java.lang.String getBuildingType() {
		return getStr("building_type");
	}

	public void setArea(java.math.BigDecimal area) {
		set("area", area);
	}
	
	public java.math.BigDecimal getArea() {
		return get("area");
	}

	public void setInnerArea(java.math.BigDecimal innerArea) {
		set("inner_area", innerArea);
	}
	
	public java.math.BigDecimal getInnerArea() {
		return get("inner_area");
	}

	public void setRealArea(java.math.BigDecimal realArea) {
		set("real_area", realArea);
	}
	
	public java.math.BigDecimal getRealArea() {
		return get("real_area");
	}

	public void setRealInnerArea(java.math.BigDecimal realInnerArea) {
		set("real_inner_area", realInnerArea);
	}
	
	public java.math.BigDecimal getRealInnerArea() {
		return get("real_inner_area");
	}

}
