package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicPaymethods<M extends BaseDicPaymethods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPaymethodId(java.lang.String paymethodId) {
		set("paymethod_id", paymethodId);
	}
	
	public java.lang.String getPaymethodId() {
		return getStr("paymethod_id");
	}

	public void setPaymethodName(java.lang.String paymethodName) {
		set("paymethod_name", paymethodName);
	}
	
	public java.lang.String getPaymethodName() {
		return getStr("paymethod_name");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}
	
	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public void setSonId(java.lang.String sonId) {
		set("son_id", sonId);
	}
	
	public java.lang.String getSonId() {
		return getStr("son_id");
	}

}
