package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynCompany<M extends BaseSynCompany<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setIsDrawback(java.lang.Boolean isDrawback) {
		set("is_drawback", isDrawback);
	}
	
	public java.lang.Boolean getIsDrawback() {
		return get("is_drawback");
	}

	public void setIsAvailable(java.lang.Boolean isAvailable) {
		set("is_available", isAvailable);
	}
	
	public java.lang.Boolean getIsAvailable() {
		return get("is_available");
	}

	public void setIsHouse(java.lang.Boolean isHouse) {
		set("is_house", isHouse);
	}
	
	public java.lang.Boolean getIsHouse() {
		return get("is_house");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

}
