package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtNeedUpload<M extends BaseDtNeedUpload<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("user_type");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setPersonalName(java.lang.String personalName) {
		set("personal_name", personalName);
	}
	
	public java.lang.String getPersonalName() {
		return getStr("personal_name");
	}

	public void setIsMain(java.lang.Integer isMain) {
		set("is_main", isMain);
	}
	
	public java.lang.Integer getIsMain() {
		return getInt("is_main");
	}

	public void setChoice(java.lang.Boolean choice) {
		set("choice", choice);
	}
	
	public java.lang.Boolean getChoice() {
		return get("choice");
	}

	public void setMaterialsId(java.lang.Integer materialsId) {
		set("materials_id", materialsId);
	}
	
	public java.lang.Integer getMaterialsId() {
		return getInt("materials_id");
	}

	public void setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
	}
	
	public java.lang.Boolean getIsDelete() {
		return get("is_delete");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}
	
	public java.lang.Integer getDataType() {
		return getInt("data_type");
	}

	public void setImageName(java.lang.String imageName) {
		set("image_name", imageName);
	}
	
	public java.lang.String getImageName() {
		return getStr("image_name");
	}

}
