package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtHouseCar<M extends BaseDtHouseCar<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setCarColor(java.lang.String carColor) {
		set("car_color", carColor);
	}
	
	public java.lang.String getCarColor() {
		return getStr("car_color");
	}

	public void setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
	}
	
	public java.lang.String getCarNumber() {
		return getStr("car_number");
	}

	public void setOrder(java.lang.String order) {
		set("order", order);
	}
	
	public java.lang.String getOrder() {
		return getStr("order");
	}

	public void setCloseStatus(java.lang.Boolean closeStatus) {
		set("close_status", closeStatus);
	}
	
	public java.lang.Boolean getCloseStatus() {
		return get("close_status");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
