package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtDetailListState<M extends BaseDtDetailListState<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDtailListId(java.lang.Integer dtailListId) {
		set("dtail_list_id", dtailListId);
	}
	
	public java.lang.Integer getDtailListId() {
		return getInt("dtail_list_id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setBelongAccount(java.lang.Integer belongAccount) {
		set("belong_account", belongAccount);
	}
	
	public java.lang.Integer getBelongAccount() {
		return getInt("belong_account");
	}

	public void setIsWatcha(java.lang.Integer isWatcha) {
		set("is_watcha", isWatcha);
	}
	
	public java.lang.Integer getIsWatcha() {
		return getInt("is_watcha");
	}

}
