package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtBankScheduling<M extends BaseDtBankScheduling<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPlanDate(java.util.Date planDate) {
		set("plan_date", planDate);
	}
	
	public java.util.Date getPlanDate() {
		return get("plan_date");
	}

	public void setPlanBank(java.lang.Integer planBank) {
		set("plan_bank", planBank);
	}
	
	public java.lang.Integer getPlanBank() {
		return getInt("plan_bank");
	}

	public void setMaxAccept(java.lang.Integer maxAccept) {
		set("max_accept", maxAccept);
	}
	
	public java.lang.Integer getMaxAccept() {
		return getInt("max_accept");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

}
