package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtUserInfoRelateValue<M extends BaseDtUserInfoRelateValue<M>> extends Model<M> implements IBean {

	public void setInfoId(java.lang.Integer infoId) {
		set("info_id", infoId);
	}
	
	public java.lang.Integer getInfoId() {
		return getInt("info_id");
	}

	public void setValueId(java.lang.Integer valueId) {
		set("value_id", valueId);
	}
	
	public java.lang.Integer getValueId() {
		return getInt("value_id");
	}

}
