package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicFormats<M extends BaseDicFormats<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFormatsCode(java.lang.String formatsCode) {
		set("formats_code", formatsCode);
	}
	
	public java.lang.String getFormatsCode() {
		return getStr("formats_code");
	}

	public void setFormatsName(java.lang.String formatsName) {
		set("formats_name", formatsName);
	}
	
	public java.lang.String getFormatsName() {
		return getStr("formats_name");
	}

	public void setIsResidential(java.lang.Boolean isResidential) {
		set("is_residential", isResidential);
	}
	
	public java.lang.Boolean getIsResidential() {
		return get("is_residential");
	}

}
