package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLoginLog<M extends BaseSysLoginLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public void setWechatId(java.lang.String wechatId) {
		set("wechat_id", wechatId);
	}
	
	public java.lang.String getWechatId() {
		return getStr("wechat_id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public void setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
	}
	
	public java.lang.String getUserAgent() {
		return getStr("user_agent");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}
	
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}
	
	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public void setLoginYear(java.lang.String loginYear) {
		set("login_year", loginYear);
	}
	
	public java.lang.String getLoginYear() {
		return getStr("login_year");
	}

	public void setLoginMonth(java.lang.String loginMonth) {
		set("login_month", loginMonth);
	}
	
	public java.lang.String getLoginMonth() {
		return getStr("login_month");
	}

	public void setLoginDate(java.lang.String loginDate) {
		set("login_date", loginDate);
	}
	
	public java.lang.String getLoginDate() {
		return getStr("login_date");
	}

}
