package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtDuty<M extends BaseDtDuty<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDutyDate(java.util.Date dutyDate) {
		set("duty_date", dutyDate);
	}
	
	public java.util.Date getDutyDate() {
		return get("duty_date");
	}

	public void setMaxServiceCount(java.lang.Integer maxServiceCount) {
		set("max_service_count", maxServiceCount);
	}
	
	public java.lang.Integer getMaxServiceCount() {
		return getInt("max_service_count");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setAmDetail(java.lang.String amDetail) {
		set("am_detail", amDetail);
	}
	
	public java.lang.String getAmDetail() {
		return getStr("am_detail");
	}

	public void setAfterDetail(java.lang.String afterDetail) {
		set("after_detail", afterDetail);
	}
	
	public java.lang.String getAfterDetail() {
		return getStr("after_detail");
	}

	public void setAfterCount(java.lang.Integer afterCount) {
		set("after_count", afterCount);
	}
	
	public java.lang.Integer getAfterCount() {
		return getInt("after_count");
	}

}
