package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtHousePersonalInformation<M extends BaseDtHousePersonalInformation<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setResidentialType(java.lang.String residentialType) {
		set("residential_type", residentialType);
	}
	
	public java.lang.String getResidentialType() {
		return getStr("residential_type");
	}

	public void setProprietorName(java.lang.String proprietorName) {
		set("proprietor_name", proprietorName);
	}
	
	public java.lang.String getProprietorName() {
		return getStr("proprietor_name");
	}

	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}

	public void setIdCard(java.lang.String idCard) {
		set("id_card", idCard);
	}
	
	public java.lang.String getIdCard() {
		return getStr("id_card");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setPostalCode(java.lang.String postalCode) {
		set("postal_code", postalCode);
	}
	
	public java.lang.String getPostalCode() {
		return getStr("postal_code");
	}

	public void setNationality(java.lang.String nationality) {
		set("nationality", nationality);
	}
	
	public java.lang.String getNationality() {
		return getStr("nationality");
	}

	public void setNational(java.lang.String national) {
		set("national", national);
	}
	
	public java.lang.String getNational() {
		return getStr("national");
	}

	public void setCultureExtent(java.lang.String cultureExtent) {
		set("culture_extent", cultureExtent);
	}
	
	public java.lang.String getCultureExtent() {
		return getStr("culture_extent");
	}

	public void setWorkUnits(java.lang.String workUnits) {
		set("work_units", workUnits);
	}
	
	public java.lang.String getWorkUnits() {
		return getStr("work_units");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}
	
	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
