package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtDetailList<M extends BaseDtDetailList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDetailListName(java.lang.String detailListName) {
		set("detail_list_name", detailListName);
	}
	
	public java.lang.String getDetailListName() {
		return getStr("detail_list_name");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setStageId(java.lang.String stageId) {
		set("stage_id", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stage_id");
	}

	public void setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

}
