package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynPaymethods<M extends BaseSynPaymethods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPaymethodId(java.lang.String paymethodId) {
		set("paymethod_id", paymethodId);
	}
	
	public java.lang.String getPaymethodId() {
		return getStr("paymethod_id");
	}

	public void setPaymethodName(java.lang.String paymethodName) {
		set("paymethod_name", paymethodName);
	}
	
	public java.lang.String getPaymethodName() {
		return getStr("paymethod_name");
	}

	public void setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
	}
	
	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public void setDiscount(java.math.BigDecimal discount) {
		set("discount", discount);
	}
	
	public java.math.BigDecimal getDiscount() {
		return get("discount");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

}
