package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynOrder<M extends BaseSynOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setOrderDate(java.util.Date orderDate) {
		set("order_date", orderDate);
	}
	
	public java.util.Date getOrderDate() {
		return get("order_date");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setOrderMoney(java.math.BigDecimal orderMoney) {
		set("order_money", orderMoney);
	}
	
	public java.math.BigDecimal getOrderMoney() {
		return get("order_money");
	}

	public void setSaler(java.lang.String saler) {
		set("saler", saler);
	}
	
	public java.lang.String getSaler() {
		return getStr("saler");
	}

	public void setIsEmployeeBuyer(java.lang.Boolean isEmployeeBuyer) {
		set("is_employee_buyer", isEmployeeBuyer);
	}
	
	public java.lang.Boolean getIsEmployeeBuyer() {
		return get("is_employee_buyer");
	}

	public void setBuildingId(java.lang.Integer buildingId) {
		set("building_id", buildingId);
	}
	
	public java.lang.Integer getBuildingId() {
		return getInt("building_id");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setPreOrderId(java.lang.String preOrderId) {
		set("pre_order_id", preOrderId);
	}
	
	public java.lang.String getPreOrderId() {
		return getStr("pre_order_id");
	}

	public void setOrderType(java.lang.String orderType) {
		set("order_type", orderType);
	}
	
	public java.lang.String getOrderType() {
		return getStr("order_type");
	}

	public void setOrderMoneyTaxFree(java.math.BigDecimal orderMoneyTaxFree) {
		set("order_money_tax_free", orderMoneyTaxFree);
	}
	
	public java.math.BigDecimal getOrderMoneyTaxFree() {
		return get("order_money_tax_free");
	}

	public void setOrderMoneyWithDiscount(java.math.BigDecimal orderMoneyWithDiscount) {
		set("order_money_with_discount", orderMoneyWithDiscount);
	}
	
	public java.math.BigDecimal getOrderMoneyWithDiscount() {
		return get("order_money_with_discount");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRebate(java.math.BigDecimal rebate) {
		set("rebate", rebate);
	}
	
	public java.math.BigDecimal getRebate() {
		return get("rebate");
	}

	public void setAreaSupplemen(java.math.BigDecimal areaSupplemen) {
		set("area_supplemen", areaSupplemen);
	}
	
	public java.math.BigDecimal getAreaSupplemen() {
		return get("area_supplemen");
	}

	public void setCompensationOperator(java.lang.String compensationOperator) {
		set("compensation_operator", compensationOperator);
	}
	
	public java.lang.String getCompensationOperator() {
		return getStr("compensation_operator");
	}

	public void setCompensationScheme(java.lang.String compensationScheme) {
		set("compensation_scheme", compensationScheme);
	}
	
	public java.lang.String getCompensationScheme() {
		return getStr("compensation_scheme");
	}

	public void setCompensationTime(java.util.Date compensationTime) {
		set("compensation_time", compensationTime);
	}
	
	public java.util.Date getCompensationTime() {
		return get("compensation_time");
	}

}
