package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtPropertyOwnersUpdate<M extends BaseDtPropertyOwnersUpdate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPropertyProportion(java.lang.String propertyProportion) {
		set("property_proportion", propertyProportion);
	}
	
	public java.lang.String getPropertyProportion() {
		return getStr("property_proportion");
	}

}
