package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynPaidMoney<M extends BaseSynPaidMoney<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPaidMoneyId(java.lang.String paidMoneyId) {
		set("paid_money_id", paidMoneyId);
	}
	
	public java.lang.String getPaidMoneyId() {
		return getStr("paid_money_id");
	}

	public void setMoneyType(java.lang.String moneyType) {
		set("money_type", moneyType);
	}
	
	public java.lang.String getMoneyType() {
		return getStr("money_type");
	}

	public void setMoneyTypeName(java.lang.String moneyTypeName) {
		set("money_type_name", moneyTypeName);
	}
	
	public java.lang.String getMoneyTypeName() {
		return getStr("money_type_name");
	}

	public void setDiedLineDate(java.util.Date diedLineDate) {
		set("died_line_date", diedLineDate);
	}
	
	public java.util.Date getDiedLineDate() {
		return get("died_line_date");
	}

	public void setUnpaidMoney(java.math.BigDecimal unpaidMoney) {
		set("unpaid_money", unpaidMoney);
	}
	
	public java.math.BigDecimal getUnpaidMoney() {
		return get("unpaid_money");
	}

	public void setTotalMoeny(java.math.BigDecimal totalMoeny) {
		set("total_moeny", totalMoeny);
	}
	
	public java.math.BigDecimal getTotalMoeny() {
		return get("total_moeny");
	}

	public void setPaidMoney(java.math.BigDecimal paidMoney) {
		set("paid_money", paidMoney);
	}
	
	public java.math.BigDecimal getPaidMoney() {
		return get("paid_money");
	}

	public void setOverflowMoney(java.math.BigDecimal overflowMoney) {
		set("overflow_money", overflowMoney);
	}
	
	public java.math.BigDecimal getOverflowMoney() {
		return get("overflow_money");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
