package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtUserMessage<M extends BaseDtUserMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}
	
	public java.lang.String getComment() {
		return getStr("comment");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}
	
	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	public void setFormId(java.lang.String formId) {
		set("form_id", formId);
	}
	
	public java.lang.String getFormId() {
		return getStr("form_id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setPage(java.lang.String page) {
		set("page", page);
	}
	
	public java.lang.String getPage() {
		return getStr("page");
	}

	public void setTemplateId(java.lang.String templateId) {
		set("template_id", templateId);
	}
	
	public java.lang.String getTemplateId() {
		return getStr("template_id");
	}

	public void setSendSuccessfully(java.lang.Boolean sendSuccessfully) {
		set("send_successfully", sendSuccessfully);
	}
	
	public java.lang.Boolean getSendSuccessfully() {
		return get("send_successfully");
	}

	public void setWhetherSend(java.lang.Boolean whetherSend) {
		set("whether_send", whetherSend);
	}
	
	public java.lang.Boolean getWhetherSend() {
		return get("whether_send");
	}

	public void setExpiration(java.util.Date expiration) {
		set("expiration", expiration);
	}
	
	public java.util.Date getExpiration() {
		return get("expiration");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setEstimatedTime(java.util.Date estimatedTime) {
		set("estimated_time", estimatedTime);
	}
	
	public java.util.Date getEstimatedTime() {
		return get("estimated_time");
	}

	public void setIsWatch(java.lang.Integer isWatch) {
		set("is_watch", isWatch);
	}
	
	public java.lang.Integer getIsWatch() {
		return getInt("is_watch");
	}

}
