package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSynServices<M extends BaseSynServices<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setServiceId(java.lang.String serviceId) {
		set("service_id", serviceId);
	}
	
	public java.lang.String getServiceId() {
		return getStr("service_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPromiseDate(java.util.Date promiseDate) {
		set("promise_date", promiseDate);
	}
	
	public java.util.Date getPromiseDate() {
		return get("promise_date");
	}

	public void setPromiseFinishDate(java.util.Date promiseFinishDate) {
		set("promise_finish_date", promiseFinishDate);
	}
	
	public java.util.Date getPromiseFinishDate() {
		return get("promise_finish_date");
	}

	public void setProcess(java.lang.String process) {
		set("process", process);
	}
	
	public java.lang.String getProcess() {
		return getStr("process");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
