package com.demo.api.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtBuildingAcceptance<M extends BaseDtBuildingAcceptance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setOrderStatus(java.lang.String orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.String getOrderStatus() {
		return getStr("order_status");
	}

	public void setSonStatus(java.lang.String sonStatus) {
		set("son_status", sonStatus);
	}
	
	public java.lang.String getSonStatus() {
		return getStr("son_status");
	}

	public void setIsAreaSenders(java.lang.Boolean isAreaSenders) {
		set("is_area_senders", isAreaSenders);
	}
	
	public java.lang.Boolean getIsAreaSenders() {
		return get("is_area_senders");
	}

	public void setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
	}
	
	public java.lang.String getCompanyId() {
		return getStr("company_id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
	}
	
	public java.lang.String getCompanyName() {
		return getStr("company_name");
	}

	public void setProjectId(java.lang.String projectId) {
		set("project_id", projectId);
	}
	
	public java.lang.String getProjectId() {
		return getStr("project_id");
	}

	public void setProjectName(java.lang.String projectName) {
		set("project_name", projectName);
	}
	
	public java.lang.String getProjectName() {
		return getStr("project_name");
	}

	public void setStageId(java.lang.String stageId) {
		set("stage_id", stageId);
	}
	
	public java.lang.String getStageId() {
		return getStr("stage_id");
	}

	public void setStageName(java.lang.String stageName) {
		set("stage_name", stageName);
	}
	
	public java.lang.String getStageName() {
		return getStr("stage_name");
	}

	public void setBuildingId(java.lang.String buildingId) {
		set("building_id", buildingId);
	}
	
	public java.lang.String getBuildingId() {
		return getStr("building_id");
	}

	public void setBuildingName(java.lang.String buildingName) {
		set("building_name", buildingName);
	}
	
	public java.lang.String getBuildingName() {
		return getStr("building_name");
	}

	public void setRoom(java.lang.String room) {
		set("room", room);
	}
	
	public java.lang.String getRoom() {
		return getStr("room");
	}

	public void setBelongAccount(java.lang.Integer belongAccount) {
		set("belong_account", belongAccount);
	}
	
	public java.lang.Integer getBelongAccount() {
		return getInt("belong_account");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		set("del_flag", delFlag);
	}
	
	public java.lang.Boolean getDelFlag() {
		return get("del_flag");
	}

	public void setBeginDeliverTime(java.util.Date beginDeliverTime) {
		set("begin_deliver_time", beginDeliverTime);
	}
	
	public java.util.Date getBeginDeliverTime() {
		return get("begin_deliver_time");
	}

	public void setActualDeliverTime(java.util.Date actualDeliverTime) {
		set("actual_deliver_time", actualDeliverTime);
	}
	
	public java.util.Date getActualDeliverTime() {
		return get("actual_deliver_time");
	}

	public void setAreaSupplementFee(java.math.BigDecimal areaSupplementFee) {
		set("area_supplement_fee", areaSupplementFee);
	}
	
	public java.math.BigDecimal getAreaSupplementFee() {
		return get("area_supplement_fee");
	}

	public void setHousekeeperId(java.lang.Integer housekeeperId) {
		set("housekeeper_id", housekeeperId);
	}
	
	public java.lang.Integer getHousekeeperId() {
		return getInt("housekeeper_id");
	}

	public void setCompletionCredentialsId(java.lang.Integer completionCredentialsId) {
		set("completion_credentials_id", completionCredentialsId);
	}
	
	public java.lang.Integer getCompletionCredentialsId() {
		return getInt("completion_credentials_id");
	}

	public void setCredentialsId(java.lang.Integer credentialsId) {
		set("credentials_id", credentialsId);
	}
	
	public java.lang.Integer getCredentialsId() {
		return getInt("credentials_id");
	}

	public void setGoodsDetailListId(java.lang.Integer goodsDetailListId) {
		set("goods_detail_list_id", goodsDetailListId);
	}
	
	public java.lang.Integer getGoodsDetailListId() {
		return getInt("goods_detail_list_id");
	}

	public void setBuildingType(java.lang.String buildingType) {
		set("building_type", buildingType);
	}
	
	public java.lang.String getBuildingType() {
		return getStr("building_type");
	}

	public void setReserveBeginDate(java.util.Date reserveBeginDate) {
		set("reserve_begin_date", reserveBeginDate);
	}
	
	public java.util.Date getReserveBeginDate() {
		return get("reserve_begin_date");
	}

	public void setReserveEndDate(java.util.Date reserveEndDate) {
		set("reserve_end_date", reserveEndDate);
	}
	
	public java.util.Date getReserveEndDate() {
		return get("reserve_end_date");
	}

}
