package com.demo.api.shortmessage.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-12T16:38:51.630+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://entinfo.cn/", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    /**
     * hello
     */
    @WebMethod(action = "http://entinfo.cn/mdgetSninfo")
    @RequestWrapper(localName = "mdgetSninfo", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.MdgetSninfo")
    @ResponseWrapper(localName = "mdgetSninfoResponse", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.MdgetSninfoResponse")
    @WebResult(name = "mdgetSninfoResult", targetNamespace = "http://entinfo.cn/")
    public java.lang.String mdgetSninfo(
        @WebParam(name = "sn", targetNamespace = "http://entinfo.cn/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://entinfo.cn/")
        java.lang.String pwd
    );

    /**
     * 发送短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容,utf-8编码;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字;msgfmt内容编码,0：ASCII串,3：短信写卡操作,4：二进制信息,8：UCS2编码,空或15：含GB汉字.返回:唯一标识
     */
    @WebMethod(action = "http://entinfo.cn/mdsmssend")
    @RequestWrapper(localName = "mdsmssend", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.Mdsmssend")
    @ResponseWrapper(localName = "mdsmssendResponse", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.MdsmssendResponse")
    @WebResult(name = "mdsmssendResult", targetNamespace = "http://entinfo.cn/")
    public java.lang.String mdsmssend(
        @WebParam(name = "sn", targetNamespace = "http://entinfo.cn/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://entinfo.cn/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://entinfo.cn/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://entinfo.cn/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://entinfo.cn/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://entinfo.cn/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://entinfo.cn/")
        java.lang.String rrid,
        @WebParam(name = "msgfmt", targetNamespace = "http://entinfo.cn/")
        java.lang.String msgfmt
    );

    /**
     * 发送个性短信：sn软件序列号;pwd加密密码md5(sn+password);mobile手机号列表，以逗号,隔开;content发送内容,utf-8编码，以逗号,隔开;ext扩展子号;stime定时时间,格式如2009-09-01 18:21:00;rrid唯一标识,全数字;msgfmt内容编码,0：ASCII串,3：短信写卡操作,4：二进制信息,8：UCS2编码,空或15：含GB汉字.返回:唯一标识
     */
    @WebMethod(action = "http://entinfo.cn/mdgxsend")
    @RequestWrapper(localName = "mdgxsend", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.Mdgxsend")
    @ResponseWrapper(localName = "mdgxsendResponse", targetNamespace = "http://entinfo.cn/", className = "com.demo.api.shortmessage.MdgxsendResponse")
    @WebResult(name = "mdgxsendResult", targetNamespace = "http://entinfo.cn/")
    public java.lang.String mdgxsend(
        @WebParam(name = "sn", targetNamespace = "http://entinfo.cn/")
        java.lang.String sn,
        @WebParam(name = "pwd", targetNamespace = "http://entinfo.cn/")
        java.lang.String pwd,
        @WebParam(name = "mobile", targetNamespace = "http://entinfo.cn/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://entinfo.cn/")
        java.lang.String content,
        @WebParam(name = "ext", targetNamespace = "http://entinfo.cn/")
        java.lang.String ext,
        @WebParam(name = "stime", targetNamespace = "http://entinfo.cn/")
        java.lang.String stime,
        @WebParam(name = "rrid", targetNamespace = "http://entinfo.cn/")
        java.lang.String rrid,
        @WebParam(name = "msgfmt", targetNamespace = "http://entinfo.cn/")
        java.lang.String msgfmt
    );
}
